2015-04-16 00:30:04.817 [error] <0.70.0> gen_server sulibarri_dht_node terminated with reason: no function clause matching sulibarri_dht_node:handle_cast({put,1,1}, []) line 49
2015-04-16 00:30:04.817 [error] <0.70.0> CRASH REPORT Process sulibarri_dht_node with 0 neighbours exited with reason: no function clause matching sulibarri_dht_node:handle_cast({put,1,1}, []) line 49 in gen_server:terminate/7 line 804
2015-04-16 00:30:04.817 [error] <0.69.0> Supervisor sulibarri_dht_sup had child sulibarri_dht_node started with sulibarri_dht_node:start_link() at <0.70.0> exit with reason no function clause matching sulibarri_dht_node:handle_cast({put,1,1}, []) line 49 in context child_terminated
2015-04-16 00:30:38.900 [error] <0.71.0> gen_server sulibarri_dht_node terminated with reason: no function clause matching sulibarri_dht_node:handle_cast({put,1,1}, []) line 49
2015-04-16 00:30:38.900 [error] <0.71.0> CRASH REPORT Process sulibarri_dht_node with 0 neighbours exited with reason: no function clause matching sulibarri_dht_node:handle_cast({put,1,1}, []) line 49 in gen_server:terminate/7 line 804
2015-04-16 00:30:38.900 [error] <0.69.0> Supervisor sulibarri_dht_sup had child sulibarri_dht_node started with sulibarri_dht_node:start_link() at <0.71.0> exit with reason no function clause matching sulibarri_dht_node:handle_cast({put,1,1}, []) line 49 in context child_terminated
2015-04-16 00:31:09.283 [error] <0.70.0> gen_server sulibarri_dht_node terminated with reason: bad argument in call to ets:insert(dht_ets, {1,1}) in sulibarri_dht_ets_store:put/2 line 12
2015-04-16 00:31:09.283 [error] <0.70.0> CRASH REPORT Process sulibarri_dht_node with 0 neighbours exited with reason: bad argument in call to ets:insert(dht_ets, {1,1}) in sulibarri_dht_ets_store:put/2 line 12 in gen_server:terminate/7 line 804
2015-04-16 00:31:09.283 [error] <0.69.0> Supervisor sulibarri_dht_sup had child sulibarri_dht_node started with sulibarri_dht_node:start_link() at <0.70.0> exit with reason bad argument in call to ets:insert(dht_ets, {1,1}) in sulibarri_dht_ets_store:put/2 line 12 in context child_terminated
2015-04-16 00:32:46.449 [error] <0.70.0> gen_server sulibarri_dht_node terminated with reason: bad argument in call to ets:insert(dht_ets, {1,1}) in sulibarri_dht_ets_store:put/2 line 12
2015-04-16 00:32:46.449 [error] <0.70.0> CRASH REPORT Process sulibarri_dht_node with 0 neighbours exited with reason: bad argument in call to ets:insert(dht_ets, {1,1}) in sulibarri_dht_ets_store:put/2 line 12 in gen_server:terminate/7 line 804
2015-04-16 00:32:46.450 [error] <0.69.0> Supervisor sulibarri_dht_sup had child sulibarri_dht_node started with sulibarri_dht_node:start_link() at <0.70.0> exit with reason bad argument in call to ets:insert(dht_ets, {1,1}) in sulibarri_dht_ets_store:put/2 line 12 in context child_terminated
2015-04-16 00:37:13.760 [error] <0.70.0> gen_server sulibarri_dht_node terminated with reason: bad argument in call to ets:insert(dht_ets, {1,1}) in sulibarri_dht_ets_store:put/2 line 13
2015-04-16 00:37:13.761 [error] <0.70.0> CRASH REPORT Process sulibarri_dht_node with 0 neighbours exited with reason: bad argument in call to ets:insert(dht_ets, {1,1}) in sulibarri_dht_ets_store:put/2 line 13 in gen_server:terminate/7 line 804
2015-04-16 00:37:13.761 [error] <0.69.0> Supervisor sulibarri_dht_sup had child sulibarri_dht_node started with sulibarri_dht_node:start_link() at <0.70.0> exit with reason bad argument in call to ets:insert(dht_ets, {1,1}) in sulibarri_dht_ets_store:put/2 line 13 in context child_terminated
2015-04-16 00:40:03.423 [error] <0.70.0> gen_server sulibarri_dht_node terminated with reason: bad argument in call to ets:insert(dht_ets, {1,1}) in sulibarri_dht_ets_store:put/2 line 13
2015-04-16 00:40:03.424 [error] <0.70.0> CRASH REPORT Process sulibarri_dht_node with 0 neighbours exited with reason: bad argument in call to ets:insert(dht_ets, {1,1}) in sulibarri_dht_ets_store:put/2 line 13 in gen_server:terminate/7 line 804
2015-04-16 00:40:03.424 [error] <0.69.0> Supervisor sulibarri_dht_sup had child sulibarri_dht_node started with sulibarri_dht_node:start_link() at <0.70.0> exit with reason bad argument in call to ets:insert(dht_ets, {1,1}) in sulibarri_dht_ets_store:put/2 line 13 in context child_terminated
2015-04-16 00:43:58.191 [error] <0.71.0> gen_server sulibarri_dht_node terminated with reason: no match of right hand value {error,not_found} in sulibarri_dht_node:handle_call/3 line 46
2015-04-16 00:43:58.192 [error] <0.71.0> CRASH REPORT Process sulibarri_dht_node with 0 neighbours exited with reason: no match of right hand value {error,not_found} in sulibarri_dht_node:handle_call/3 line 46 in gen_server:terminate/7 line 804
2015-04-16 00:43:58.192 [error] <0.69.0> Supervisor sulibarri_dht_sup had child sulibarri_dht_node started with sulibarri_dht_node:start_link() at <0.71.0> exit with reason no match of right hand value {error,not_found} in sulibarri_dht_node:handle_call/3 line 46 in context child_terminated
2015-04-16 00:47:27.072 [error] <0.70.0> gen_server sulibarri_dht_node terminated with reason: no match of right hand value {error,not_found} in sulibarri_dht_node:handle_call/3 line 46
2015-04-16 00:47:27.072 [error] <0.70.0> CRASH REPORT Process sulibarri_dht_node with 0 neighbours exited with reason: no match of right hand value {error,not_found} in sulibarri_dht_node:handle_call/3 line 46 in gen_server:terminate/7 line 804
2015-04-16 00:47:27.072 [error] <0.69.0> Supervisor sulibarri_dht_sup had child sulibarri_dht_node started with sulibarri_dht_node:start_link() at <0.70.0> exit with reason no match of right hand value {error,not_found} in sulibarri_dht_node:handle_call/3 line 46 in context child_terminated
2015-04-16 11:47:28.317 [error] <0.76.0> gen_server sulibarri_dht_node terminated with reason: {'module could not be loaded',[{bet_adm,ping,[nodeA@localhost],[]},{sulibarri_dht_node,handle_call,3,[{file,"src/sulibarri_dht_node.erl"},{line,58}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,607}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,639}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}
2015-04-16 11:47:28.317 [error] <0.76.0> CRASH REPORT Process sulibarri_dht_node with 0 neighbours exited with reason: call to undefined function bet_adm:ping(nodeA@localhost) in gen_server:terminate/7 line 804
2015-04-16 11:47:28.317 [error] <0.75.0> Supervisor sulibarri_dht_sup had child sulibarri_dht_node started with sulibarri_dht_node:start_link() at <0.76.0> exit with reason call to undefined function bet_adm:ping(nodeA@localhost) in context child_terminated
